name: find_unmaintained_packages
on:
  workflow_dispatch

jobs:
  package_maintenance_job:
    name: A job to check sbt project dependencies maintenance
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
      - name: Check dependencies maintenance
        id: package-maintenance
        uses: package-maintenance-dev/github-action@v0.0.1-SNAPSHOT
